[tool.commitizen]
version = "0.0.1"
version_files = [
    "src/mdv/__version__.py",
    "pyproject.toml",
]
name = "cz_conventional_commits"
tag_format = "v$version"
bump_message = "bump: $current_version â†’ $new_version [skip-ci]"
